const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();
const port = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// In-memory store to simulate database for payments
const payments = {};

// Create a router to namespace the API endpoints
const apiRouter = express.Router();

/**
 * Endpoint for the frontend to call when the Pi SDK is ready for server approval.
 */
apiRouter.post('/approve_payment', (req, res) => {
  const { paymentId } = req.body;
  if (!paymentId) {
    return res.status(400).json({ error: 'paymentId is required' });
  }

  console.log(`[SERVER] Received approval request for paymentId: ${paymentId}`);

  // Simulate storing the payment state
  payments[paymentId] = { status: 'approved' };
  
  // TODO: In a real app, you would make a POST request to Pi Network API here

  console.log(`[SERVER] Simulated approval for paymentId: ${paymentId}`);
  res.json({ success: true, message: 'Payment approved for processing.' });
});

/**
 * Endpoint for the frontend to call when the Pi SDK is ready for server completion.
 */
apiRouter.post('/complete_payment', (req, res) => {
  const { paymentId, txid } = req.body;
  if (!paymentId || !txid) {
    return res.status(400).json({ error: 'paymentId and txid are required' });
  }
  
  console.log(`[SERVER] Received completion request for paymentId: ${paymentId} with txid: ${txid}`);

  // Check if payment was 'approved' first
  if (!payments[paymentId] || payments[paymentId].status !== 'approved') {
    return res.status(400).json({ error: 'Payment not approved or not found.' });
  }

  // Simulate updating the payment state
  payments[paymentId].status = 'completed';
  payments[paymentId].txid = txid;

  console.log(`[SERVER] Simulated completion for paymentId: ${paymentId}`);
  console.log(`[SERVER] Product/Service delivered for paymentId: ${paymentId}`);

  res.json({ success: true, message: 'Payment completed and product delivered.' });
});

// Mount the API router at the /api prefix
app.use('/api', apiRouter);

// Serve static files from the 'dist' directory (generated by 'npm run build')
app.use(express.static(path.join(__dirname, 'dist')));

// Handle React routing, return all requests to React app
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(port, () => {
  console.log(`Architex backend server listening on port ${port}`);
});